In [1]:
import numpy as np
import pandas as pd

In [2]:
filename = 'data/서울시 자치구 년도별 CCTV 설치 현황_221231기준.csv'
cctv = pd.read_csv(filename, encoding='euc-kr',thousands=',')
colums = '구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년'.split(',')
cctv=cctv[colums]
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,2804,3097,3981,6576,8850,11566,11024,13151,11912,9144,9236
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232

In [3]:
cctv.drop([cctv.index[0]],inplace=True)
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232
5,광진구,3480,507,82,84,64,21,465,443,709,172,662,271

In [4]:
temp1 = cctv.iloc[:,10:13].sum(axis=1)
temp2 = cctv.iloc[:,2:10].sum(axis=1)
cctv['최근증가율'] = (temp1/temp2 * 100).round(2)
cctv.head()

,구분,총계,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,최근증가율
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291,46.23
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137,53.54
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334,93.94
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232,36.58
5,광진구,3480,507,82,84,64,21,465,443,709,172,662,271,46.53

In [5]:
cctv = cctv.rename(columns={'구분': '구별','총계': 'CCTV댓수'})
cctv.head()

,구별,CCTV댓수,2013년 이전 설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,최근증가율
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291,46.23
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137,53.54
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334,93.94
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232,36.58
5,광진구,3480,507,82,84,64,21,465,443,709,172,662,271,46.53

In [6]:
cols = '구별 CCTV댓수 최근증가율'.split()
cctv = cctv[cols]
cctv.head()

    구별  CCTV댓수  최근증가율
1  종로구    1980  46.23
2  중 구    2584  53.54
3  용산구    2847  93.94
4  성동구    4047  36.58
5  광진구    3480  46.53

In [7]:
cctv.to_csv('data/cctv.csv', index=False, encoding='euc-kr')