In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data/서울시인구.txt',sep='\t', thousands=',')
df.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2021,합계,"4,426,007","9,736,027","4,721,977","5,014,050","9,509,458","4,618,040","4,891,418","226,569","103,937","122,632",2.15,"1,605,416"
3,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
4,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"

In [3]:
df.drop([df.index[0]],inplace=True)
df.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2021,합계,"4,426,007","9,736,027","4,721,977","5,014,050","9,509,458","4,618,040","4,891,418","226,569","103,937","122,632",2.15,"1,605,416"
3,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
4,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"
5,2021,용산구,"111,036","237,285","115,085","122,200","222,953","107,210","115,743","14,332","7,875","6,457",2.01,"39,070"

In [4]:
df.drop([df.index[0]],inplace=True)
df.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
2,2021,합계,"4,426,007","9,736,027","4,721,977","5,014,050","9,509,458","4,618,040","4,891,418","226,569","103,937","122,632",2.15,"1,605,416"
3,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
4,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"
5,2021,용산구,"111,036","237,285","115,085","122,200","222,953","107,210","115,743","14,332","7,875","6,457",2.01,"39,070"
6,2021,성동구,"134,233","292,672","142,259","150,413","285,990","139,380","146,610","6,682","2,879","3,803",2.13,"46,380"

In [5]:
df.drop([df.index[0]],inplace=True)
df.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
3,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
4,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"
5,2021,용산구,"111,036","237,285","115,085","122,200","222,953","107,210","115,743","14,332","7,875","6,457",2.01,"39,070"
6,2021,성동구,"134,233","292,672","142,259","150,413","285,990","139,380","146,610","6,682","2,879","3,803",2.13,"46,380"
7,2021,광진구,"167,949","352,627","169,317","183,310","339,996","164,058","175,938","12,631","5,259","7,372",2.02,"51,723"

In [6]:
temp_index = []
for i in range(len(df.index)):
    temp_index.append(i)
print(temp_index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [7]:
df.index = temp_index
df.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
1,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"
2,2021,용산구,"111,036","237,285","115,085","122,200","222,953","107,210","115,743","14,332","7,875","6,457",2.01,"39,070"
3,2021,성동구,"134,233","292,672","142,259","150,413","285,990","139,380","146,610","6,682","2,879","3,803",2.13,"46,380"
4,2021,광진구,"167,949","352,627","169,317","183,310","339,996","164,058","175,938","12,631","5,259","7,372",2.02,"51,723"

In [8]:
df = df.rename(columns={'자치구': '구별'})
df = df.rename(columns={'인구': '인구수'})
df = df.rename(columns={'인구.3': '내국인'})
df = df.rename(columns={'인구.6': '외국인'})
df.head()

,기간,구별,세대,인구수,인구.1,인구.2,내국인,인구.4,인구.5,외국인,인구.7,인구.8,세대당인구,65세이상고령자
0,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
1,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"
2,2021,용산구,"111,036","237,285","115,085","122,200","222,953","107,210","115,743","14,332","7,875","6,457",2.01,"39,070"
3,2021,성동구,"134,233","292,672","142,259","150,413","285,990","139,380","146,610","6,682","2,879","3,803",2.13,"46,380"
4,2021,광진구,"167,949","352,627","169,317","183,310","339,996","164,058","175,938","12,631","5,259","7,372",2.02,"51,723"

In [9]:
df.인구수 = df.인구수.str.replace(',','').astype(int)
df.외국인 = df.외국인.str.replace(',','').astype(int)
df['65세이상고령자'] = df['65세이상고령자'].str.replace(',','').astype(int)
df.head()

,기간,구별,세대,인구수,인구.1,인구.2,내국인,인구.4,인구.5,외국인,인구.7,인구.8,세대당인구,65세이상고령자
0,2021,종로구,"73,494",153789,"74,186","79,603","144,683","70,183","74,500",9106,"4,003","5,103",1.97,27818
1,2021,중구,"63,519",131787,"64,083","67,704","122,499","59,630","62,869",9288,"4,453","4,835",1.93,24392
2,2021,용산구,"111,036",237285,"115,085","122,200","222,953","107,210","115,743",14332,"7,875","6,457",2.01,39070
3,2021,성동구,"134,233",292672,"142,259","150,413","285,990","139,380","146,610",6682,"2,879","3,803",2.13,46380
4,2021,광진구,"167,949",352627,"169,317","183,310","339,996","164,058","175,938",12631,"5,259","7,372",2.02,51723

In [10]:
df['외국인비율'] = (df.외국인/df.인구수*100).round(2) 
df['고령자비율'] = (df['65세이상고령자']/df.인구수*100).round(2)
df.head()

,기간,구별,세대,인구수,인구.1,인구.2,내국인,인구.4,인구.5,외국인,인구.7,인구.8,세대당인구,65세이상고령자,외국인비율,고령자비율
0,2021,종로구,"73,494",153789,"74,186","79,603","144,683","70,183","74,500",9106,"4,003","5,103",1.97,27818,5.92,18.09
1,2021,중구,"63,519",131787,"64,083","67,704","122,499","59,630","62,869",9288,"4,453","4,835",1.93,24392,7.05,18.51
2,2021,용산구,"111,036",237285,"115,085","122,200","222,953","107,210","115,743",14332,"7,875","6,457",2.01,39070,6.04,16.47
3,2021,성동구,"134,233",292672,"142,259","150,413","285,990","139,380","146,610",6682,"2,879","3,803",2.13,46380,2.28,15.85
4,2021,광진구,"167,949",352627,"169,317","183,310","339,996","164,058","175,938",12631,"5,259","7,372",2.02,51723,3.58,14.67

In [11]:
df.drop(columns=['기간','세대','인구.1','인구.2','인구.4','인구.5','인구.7','인구.8','세대당인구','65세이상고령자'],inplace=True)
df.head()

    구별     인구수      내국인    외국인  외국인비율  고령자비율
0  종로구  153789  144,683   9106   5.92  18.09
1   중구  131787  122,499   9288   7.05  18.51
2  용산구  237285  222,953  14332   6.04  16.47
3  성동구  292672  285,990   6682   2.28  15.85
4  광진구  352627  339,996  12631   3.58  14.67

In [13]:
df.to_csv('data/pop.csv', index=False, encoding='euc-kr')